[workspace]
resolver = "2"
members = ["crates/plotnik-cli", "crates/plotnik-lib", "crates/plotnik-langs", "crates/plotnik-core"]

[workspace.package]
version = "0.2.2"
license = "Apache-2.0"
repository = "https://github.com/plotnik-lang/plotnik"
edition = "2024"

[workspace.dependencies]
plotnik-core = { path = "crates/plotnik-core", version = "0.2.2" }
plotnik-langs = { path = "crates/plotnik-langs", version = "0.2.2" }
plotnik-lib = { path = "crates/plotnik-lib", version = "0.2.2" }
