[package]
name = "plotnik-core"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "Core data structures for Plotnik"
repository = "https://github.com/plotnik-lang/plotnik"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"