[term]
quiet = true

[alias]
coverage = "llvm-cov --all-features --workspace"
coverage-html = "llvm-cov --all-features --workspace --html --open"
coverage-lcov = "llvm-cov --all-features --workspace --lcov --output-path lcov.info"
