name: release

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@efa25f7f19611383d5b0ccf2d1c8914531636bf9 # stable
        with:
          toolchain: stable
          components: clippy

      - name: Using Rust cache
        uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
        with:
          cache-all-crates: "true"

      - name: Check
        run: cargo check --workspace --all-targets

      - name: Clippy
        run: cargo clippy --workspace --all-targets -- -D warnings

      - name: Test
        run: cargo test --workspace

  publish:
    needs: verify
    runs-on: ubuntu-latest
    environment: crates-io
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@efa25f7f19611383d5b0ccf2d1c8914531636bf9 # stable
        with:
          toolchain: stable

      - name: Publish to crates.io
        uses: katyo/publish-crates@02cc2f1ad653fb25c7d1ff9eb590a8a50d06186b # v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  bump-patch:
    needs: publish
    uses: ./.github/workflows/bump.yml
    with:
      bump: patch
    secrets:
      PLOTNIK_PAT: ${{ secrets.PLOTNIK_PAT }}
    permissions:
      contents: write
      pull-requests: write
